name: jest-ci

on: push

jobs:
    test-back:
        runs-on: ubuntu-latest
        env:
            JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
            EMAIL_OAUTH_CLIENTID: ${{secrets.EMAIL_OAUTH_CLIENTID}}
            EMAIL_OAUTH_CLIENT_SECRET: ${{secrets.EMAIL_OAUTH_CLIENT_SECRET}}
            EMAIL_OAUTH_REFRESH_TOKEN: ${{secrets.EMAIL_OAUTH_REFRESH_TOKEN}}
            EMAIL_OAUTH_ACCESS_TOKEN: ${{secrets.EMAIL_OAUTH_ACCESS_TOKEN}}
            EMAIL_USERNAME: ${{secrets.EMAIL_USERNAME}}
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Goto back and run tests
              run: |
                  sed -i "s/JWT_SECRET_KEY/${{ env.JWT_SECRET_KEY }}/g" docker-compose.integration.test.yml 
                  sed -i "s/EMAIL_OAUTH_CLIENTID/${{ env.EMAIL_OAUTH_CLIENTID }}/g" docker-compose.integration.test.yml 
                  sed -i "s/EMAIL_OAUTH_CLIENT_SECRET/${{ env.EMAIL_OAUTH_CLIENT_SECRET }}/g" docker-compose.integration.test.yml 
                  sed -i "s/EMAIL_OAUTH_REFRESH_TOKEN/${{ env.EMAIL_OAUTH_REFRESH_TOKEN }}/g" docker-compose.integration.test.yml 
                  sed -i "s/EMAIL_OAUTH_ACCESS_TOKEN/${{ env.EMAIL_OAUTH_ACCESS_TOKEN }}/g" docker-compose.integration.test.yml 
                  sed -i "s/EMAIL_USERNAME/${{ env.EMAIL_USERNAME }}/g" docker-compose.integration.test.yml 
                  docker-compose -f up docker-compose.integration.test.yml --build --exit-code-from testrunner
    # docker:
    #     needs: test-back
    #     if: github.ref == 'refs/heads/dev'
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Set up QEMU
    #           uses: docker/setup-qemu-action@v2
    #         - name: Set up Docker Buildx
    #           uses: docker/setup-buildx-action@v2
    #         - name: Login to Docker Hub
    #           uses: docker/login-action@v2
    #           with:
    #               username: ${{ secrets.DOCKERHUB_USERNAME }}
    #               password: ${{ secrets.DOCKERHUB_TOKEN }}
    #         - name: Build and push
    #           uses: docker/build-push-action@v4
    #           with:
    #               push: true
    #               context: "{{defaultContext}}:client"
    #               tags: witzkvn/wildcarbon:latest
